### ISSUE TITLE
[Improvement] Don't use subprocess/sys.executable to call the vehicle model generator

### ISSUE THREAD

**Issue by vasilvas99** [eclipse-velocitas/devenv-devcontainer-setup#21]
# Description

The [generate_model.py](https://github.com/eclipse-velocitas/devenv-devcontainer-setup/blob/main/vehicle-model-lifecycle/src/generate_model.py) is an useful script not only for setting up devcontainers but as a helper when generating the vehicle model during container build time of  a vapp (e.g. [Seat-Adjuster Example @ Leda - Examples](https://github.com/eclipse-leda/leda-example-applications/blob/main/seat-adjuster/Dockerfile)).

It however uses `subprocess.check_call()` to run `sdv.model_generator.main` with the appropriate arguments as a separate shell process, one of them being `sys.executable`, which should be the path to the current Python executable. 

`sys.executable` however uses argv[0] and other environment variables (e.g. PYTHONEXECUTABLE) to determine said path and might not be always reliable.  

For example when building [Seat-Adjuster Example @ Leda - Examples](https://github.com/eclipse-leda/leda-example-applications/blob/main/seat-adjuster/Dockerfile#L43) `sys.executable` resolves to `/usr/bin/python`, but the system python binary for the build host is at `/usr/bin/python3`, therefore requiring us to first install `python-is-python3` that symlinks python to python3.

# Possible improvement

Instead of calling **sdv.model_generator.main** as a shell sub-process, import it is a python module and call its **main()** function directly with the required cli arguments (running a separate shell process no longer required).

To implement this, the following modifications to [sdv.model_generator.main](https://github.com/eclipse-velocitas/vehicle-model-generator/blob/main/sdv/model_generator/main.py) will be required:

1. Make main() take an optional list of arguments (default `None`)

```python3
def main(cli_args = None):
    ...
```
2. Pass cli_args to `parser.parse_args(args=cli_args)` (ref: [The parse_args() method](https://docs.python.org/3/library/argparse.html#the-parse-args-method)):

```python3
    ...
    args = parser.parse_args(args=cli_args) # when cli_args = None, it defaults to sys.argv, otherwise it parses the provided list of arguments

    strict = args.strict

    include_dirs = ["."]
    include_dirs.extend(args.include_dir)
    ...
```

**Comment by dennismeister93** [comment]
Hi @vasilvas99 thanks for notifying us! We will have an internal discussion about that and added this to our backlog now! :)

**Comment by mml5bg** [comment]
Hi @vasilvas99, generating model using cli command `velocitas init` is not proposed way. Proposed way for model generation is to use a tool https://github.com/eclipse-velocitas/vehicle-model-generator, please have a look on it and give us feedback. In case, you need further support, feel free to contact us!

**Comment by mml5bg** [comment]
Hi @vasilvas99, generating model using `velocitas init` is not proposed. Proposed way to generate vehicle model is to use tool we develop for that purpose https://github.com/eclipse-velocitas/vehicle-model-generator. Please try it and provide us feedback. In case, you need further support, don't hesitate to contact us.

**Comment by vasilvas99** [comment]
@mml5bg @kse3hi tested your suggestion and a few other base containers, can report the following:

- vehicle model generator works as expected and seems to really be the proper way to do what we wanted  (skips the whole dapr setup etc) 
- tested different versions of the ubuntu container and `FROM ubuntu:22.04` seems to work well (the base for your devcontainer)
- when working with `FROM ubuntu:latest` (or no tag) in the dockerfile the python-is-python3 symlink is needed
- played around a bit with a debian:latest container and the issue is not present

Given that this is more related to the environment rather than `velocitas init` itself and that vehicle-model-generator exsits, I think you can close the present issue.

**Comment by kse3hi** [comment]
Thank you @vasilvas99  for collaboration.
